Added PR Approver workflow
GuilleAmutio/platy-desktop pull request #43
Opened 2022-07-06 08:19 UTC by pabferir

2022-07-06 10:53 UTC, GuilleAmutio requested changes

2022-07-06 10:53 UTC, GuilleAmutio commented on .github/workflows/pr-approver.yml
> +      - uses: tauri-apps/tauri-action@v0
Add also `linting` step after `build` step, like:
```
- name: Linting app
  run: yarn lint
```

2022-07-06 10:53 UTC, GuilleAmutio commented on .github/workflows/pr-approver.yml
> +    types: [ opened, reopened ]
Add `edited` and `synchronize` types

2022-07-06 10:53 UTC, GuilleAmutio commented on .github/workflows/pr-approver.yml
> +          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
Will have to add a sonar-project.properties file in the root directory as here we are not defining the projectKey, sources to be analyzed, tests, coveragePath...

2022-07-06 11:00 UTC, GuilleAmutio commented
Could also be interesting to add a CODEOWNERS file inside the `.github` folder in order to request approval from @Joolmo @jbellver99  you and me. An example can be found at https://github.com/spacedriveapp/spacedrive/blob/main/.github/CODEOWNERS

2022-07-06 12:25 UTC, pabferir commented on .github/workflows/pr-approver.yml
> +  repository_dispatch:
I added it to be able to manually trigger and test it for the first time now that is on the repo. It will be removed after.

2022-07-06 13:04 UTC, GuilleAmutio approved these changes

2022-07-07 06:58 UTC, GuilleAmutio commented
By the way, an extra pipeline has to be created when on push to `main` branch in order to execute the SonarCloud analysis based on the main branch

2022-07-07 07:07 UTC, GuilleAmutio commented
Check this out, it might help you https://docs.sonarcloud.io/improving/pull-request-analysis/

2022-07-07 10:06 UTC, GuilleAmutio approved these changes

2022-07-07 10:08 UTC, merged